version: '3'
services: 
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose: 
      - 80
    restart: unless-stopped
    networks:
      - nginx-proxy
      - backend
    env_file: .env

networks:
  backend:
  nginx-proxy:
    external: true
